name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Add the necessary permissions for the access token
        # Refer to the Docker documentation for the specific scopes required
        # https://docs.docker.com/docker-hub/access-tokens/
        # e.g., permissions: "read:repo_tag,write:repo"
        permissions: |
          pull
          push
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ayman_gfg:latest
          ${{ secrets.DOCKER_USERNAME }}/ayman_gfg:${{ github.sha }}
