name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        permissions: |
          pull
          push

    - name: Docker info
      run: |
        docker info
        docker version

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ayman_gfg:latest
          ${{ secrets.DOCKER_USERNAME }}/ayman_gfg:${{ github.sha }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Debug Buildx
      run: |
        echo "Buildx driver: ${{ steps.buildx.outputs.driver }}"
        echo "Buildx platforms: ${{ steps.buildx.outputs.platforms }}"
          
